// Fabric Efficiency Ledger - fabric topology, sources, generations, scopes.
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0.
#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include "fel/checked.hpp"
#include "fel/id.hpp"
#include "fel/time.hpp"

namespace fel {

// The provenance classification of a telemetry source. Every result produced by
// the ledger carries the set of provenance classes that contributed to it, so a
// consumer can always tell real measured telemetry from synthetic input and
// from claims the runtime explicitly does not support.
enum class ProvenanceClass : std::uint8_t {
  Real = 1,         // measured by a real reporting agent
  Synthetic = 2,    // generated by a model, simulator, or test harness
  Replay = 3,       // replayed from a recorded archive
  Unsupported = 4,  // declared but not supported by this runtime: never counted
};

inline constexpr std::size_t kProvenanceClassCount = 4;

[[nodiscard]] std::string_view provenance_class_name(ProvenanceClass value) noexcept;
[[nodiscard]] std::optional<ProvenanceClass> provenance_class_from_name(std::string_view name) noexcept;
// True when the class may contribute to accounting totals at all. Unsupported
// sources are recorded but never produce numbers.
[[nodiscard]] bool provenance_is_countable(ProvenanceClass value) noexcept;

enum class SourceKind : std::uint8_t {
  SwitchCounter = 1,
  PortCounter = 2,
  QueueCounter = 3,
  FlowSampler = 4,
  ReservationController = 5,
  PathProbe = 6,
  SyntheticGenerator = 7,
  ReplayArchive = 8,
  ManualEntry = 9,
};

[[nodiscard]] std::string_view source_kind_name(SourceKind kind) noexcept;
[[nodiscard]] std::optional<SourceKind> source_kind_from_name(std::string_view name) noexcept;

struct Source {
  SourceId id;
  std::string label;
  SourceKind kind = SourceKind::SwitchCounter;
  AuthorityRank authority;
  ProvenanceClass provenance = ProvenanceClass::Real;
  bool enabled = true;
};

// A bounded lifetime of a reporting agent. Evidence is only accepted from an
// incarnation whose interval covers the receive time.
struct SourceIncarnation {
  IncarnationId id;
  SourceId source;
  EpochId boot_epoch;
  TimePoint started_at;
  std::optional<TimePoint> retired_at;
  std::string note;

  [[nodiscard]] bool covers(TimePoint when) const noexcept {
    if (when < started_at) return false;
    if (retired_at.has_value() && when > *retired_at) return false;
    return true;
  }
  [[nodiscard]] bool is_retired() const noexcept { return retired_at.has_value(); }
};

enum class GenerationState : std::uint8_t {
  Active = 1,
  Superseded = 2,
};

[[nodiscard]] std::string_view generation_state_name(GenerationState state) noexcept;

// A fabric generation: a configuration epoch of the fabric. Usage reported for
// a superseded generation must never be attached to the resources of the
// current generation.
struct Generation {
  GenerationId id;
  Ordinal ordinal;
  std::string label;
  TimePoint effective_from;
  std::optional<TimePoint> effective_to;
  GenerationState state = GenerationState::Active;
};

// Binds a stable resource identity to a fabric generation for a time interval.
// Evidence is only correlated to a resource when a binding exists for the
// (resource, generation) pair and the interval covers the observation time.
struct GenerationBinding {
  BindingId id;
  ResourceId resource;
  GenerationId generation;
  TimePoint valid_from;
  std::optional<TimePoint> valid_to;
};

enum class ScopeKind : std::uint8_t {
  Fabric = 1,
  Pod = 2,
  Switch = 3,
  Port = 4,
  Queue = 5,
  Flow = 6,
  Reservation = 7,
  Other = 8,
};

inline constexpr std::size_t kScopeKindCount = 8;

[[nodiscard]] std::string_view scope_kind_name(ScopeKind kind) noexcept;
[[nodiscard]] std::optional<ScopeKind> scope_kind_from_name(std::string_view name) noexcept;

// A node of the reporting hierarchy. Resources are attached to exactly one
// scope; a scope total is the sum of its own members and the totals of its
// children, which keeps hierarchical rollups free of double counting.
struct Scope {
  ScopeId id;
  std::string label;
  ScopeKind kind = ScopeKind::Fabric;
  std::optional<ScopeId> parent;
  std::vector<ResourceId> members;
};

enum class ResourceKind : std::uint8_t {
  Port = 1,
  Queue = 2,
  Link = 3,
  Device = 4,
  Buffer = 5,
  Other = 6,
};

[[nodiscard]] std::string_view resource_kind_name(ResourceKind kind) noexcept;
[[nodiscard]] std::optional<ResourceKind> resource_kind_from_name(std::string_view name) noexcept;

struct Resource {
  ResourceId id;
  std::string label;
  ResourceKind kind = ResourceKind::Port;
  ScopeId scope;
  std::string locality;  // opaque, operator supplied location label
};

struct Flow {
  FlowId id;
  std::string label;
  ScopeId scope;
  GenerationId generation;
  std::vector<ResourceId> path_hint;  // bounded list of resources
};

struct Path {
  PathId id;
  std::string label;
  ScopeId scope;
  GenerationId generation;
  std::vector<ResourceId> hops;  // bounded ordered list
};

struct Reservation {
  ReservationId id;
  std::string label;
  ScopeId scope;
  GenerationId generation;
  std::optional<ResourceId> resource;
  std::uint64_t reserved_capacity_nanos = 0;
  TimePoint valid_from;
  std::optional<TimePoint> valid_to;
};

// The immutable topology document. Revisions are content addressed, so a result
// can always be re-derived against the exact topology that produced it.
class FabricTopology {
 public:
  FabricTopology() = default;

  [[nodiscard]] Result<void> add_generation(Generation generation);
  [[nodiscard]] Result<void> add_source(Source source);
  [[nodiscard]] Result<void> add_incarnation(SourceIncarnation incarnation);
  [[nodiscard]] Result<void> add_scope(Scope scope);
  [[nodiscard]] Result<void> add_resource(Resource resource);
  [[nodiscard]] Result<void> add_binding(GenerationBinding binding);
  [[nodiscard]] Result<void> add_flow(Flow flow);
  [[nodiscard]] Result<void> add_path(Path path);
  [[nodiscard]] Result<void> add_reservation(Reservation reservation);

  // Full structural validation: hierarchy is a forest, resources belong to one
  // scope each, incarnation intervals do not overlap per source, bindings are
  // non-overlapping per (resource, generation).
  [[nodiscard]] Result<void> validate() const;

  [[nodiscard]] const Source* find_source(const SourceId& id) const noexcept;
  [[nodiscard]] const SourceIncarnation* find_incarnation(const IncarnationId& id) const noexcept;
  [[nodiscard]] const Generation* find_generation(const GenerationId& id) const noexcept;
  [[nodiscard]] const Scope* find_scope(const ScopeId& id) const noexcept;
  [[nodiscard]] const Resource* find_resource(const ResourceId& id) const noexcept;
  [[nodiscard]] const Flow* find_flow(const FlowId& id) const noexcept;
  [[nodiscard]] const Path* find_path(const PathId& id) const noexcept;
  [[nodiscard]] const Reservation* find_reservation(const ReservationId& id) const noexcept;

  [[nodiscard]] bool generation_binds(const ResourceId& resource, const GenerationId& generation,
                                      TimePoint when) const noexcept;

  // Depth first, ascending identity order. Deterministic by construction.
  [[nodiscard]] std::vector<ScopeId> children_of(const ScopeId& id) const;
  [[nodiscard]] std::vector<ScopeId> descendants_of(const ScopeId& id) const;
  [[nodiscard]] std::vector<ScopeId> ancestors_of(const ScopeId& id) const;
  [[nodiscard]] std::vector<ResourceId> resources_of(const ScopeId& id, bool include_descendants) const;
  [[nodiscard]] std::vector<ScopeId> all_scope_ids() const;
  [[nodiscard]] std::vector<GenerationId> all_generation_ids() const;

  [[nodiscard]] const std::map<GenerationId, Generation>& generations() const noexcept {
    return generations_;
  }
  [[nodiscard]] const std::map<SourceId, Source>& sources() const noexcept { return sources_; }
  [[nodiscard]] const std::map<IncarnationId, SourceIncarnation>& incarnations() const noexcept {
    return incarnations_;
  }
  [[nodiscard]] const std::map<ScopeId, Scope>& scopes() const noexcept { return scopes_; }
  [[nodiscard]] const std::map<ResourceId, Resource>& resources() const noexcept {
    return resources_;
  }
  [[nodiscard]] const std::map<FlowId, Flow>& flows() const noexcept { return flows_; }
  [[nodiscard]] const std::map<PathId, Path>& paths() const noexcept { return paths_; }
  [[nodiscard]] const std::map<ReservationId, Reservation>& reservations() const noexcept {
    return reservations_;
  }
  [[nodiscard]] const std::vector<GenerationBinding>& bindings() const noexcept { return bindings_; }

  [[nodiscard]] std::size_t size() const noexcept;

  // Canonical, key sorted serialization used for revision hashing.
  [[nodiscard]] std::string canonical_form() const;
  [[nodiscard]] Digest256 digest() const;
  [[nodiscard]] TopologyRevisionId revision_id() const;

 private:
  [[nodiscard]] Result<void> check_resource_membership(const ResourceId& resource,
                                                      const ScopeId& scope,
                                                      const ScopeId* ignore_scope) const;

  std::map<GenerationId, Generation> generations_;
  std::map<SourceId, Source> sources_;
  std::map<IncarnationId, SourceIncarnation> incarnations_;
  std::map<ScopeId, Scope> scopes_;
  std::map<ResourceId, Resource> resources_;
  std::vector<GenerationBinding> bindings_;
  std::map<FlowId, Flow> flows_;
  std::map<PathId, Path> paths_;
  std::map<ReservationId, Reservation> reservations_;
};

}  // namespace fel
